#!/usr/bin/env bash
docker run --rm --network="host" mongo:3.6 mongo --quiet --eval "db.adminCommand('listDatabases').databases.forEach(function(db) { print(db.name + '\t' + (db.sizeOnDisk / (1024*1024*1024)).toFixed(3) + 'GB'); })"
